#!/bin/bash

# Name: ssswitch
# Version: v1.1
# Editor: Sam

# configure your superset ip address and port
# IP_ADDRESS="192.168.0.1"
IP_ADDRESS="192.168.201.177"
# PORT="8787"
PORT="8787"


# check ip address
test_flag=0
ip_list=$(ifconfig | grep "inet " | awk '{print $2}')
for i in $ip_list
do 
  if [ $i = $IP_ADDRESS ]
  then
    test_flag=1
  fi
done

if [ $test_flag != 1 ]
then
  echo -e "\033[31;1m$IP_ADDRESS doesn't exist in this device.\033[0m."
  exit 1
fi


function start(){
  condition=$(ps -ef | awk '/gunicorn/ && !/awk/{print $2}' | wc -l)
  #echo $condition
  if [[ $condition -eq 0 ]]
  then
    gunicorn --workers 5 --timeout 120 --bind $IP_ADDRESS:$PORT "superset.app:create_app()" --daemon
    if [[ $? -eq 0 ]]
    then 
      echo -e "\033[32;1mSuperset has been launched.\033[0m"
    else
      echo -e "\033[31;1mError happened when launching the superset.\033[0m"
    fi
  else
    echo -e "\033[32;1mSuperset is running now.\033[0m"
  fi
  exit 0
}

function stop(){
  condition=$(ps -ef | awk '/gunicorn/ && !/awk/{print $2}' | wc -l)
  if [[ $condition -eq 0 ]]
  then
    echo -e "\033[32;1mSuperset is not running.\033[0m"
  else
    ps -ef | awk '/superset/ && !/awk/{print $2}' | xargs kill -9
    if [[ $? -eq 0 ]]
    then
      echo -e "\033[32;1mSuperset has been ceased just now.\033[0m"
    else
      echo -e "\033[31;1mError happened when ceasing the superset.\033[0m"
    fi
  fi
}

function superset_status(){
  condition=$(ps -ef | awk '/gunicorn/ && !/awk/{print $2}' | wc -l)
  if [[ $condition -eq 0 ]]
  then
    echo "Superset is not running."
  else
    echo "Superset is running now."
  fi
}

function superset_restart(){
  condition=$(ps -ef | awk '/gunicorn/ && !/awk/{print $2}' | wc -l)
  if [[ $condition -eq 0 ]]
  then
    gunicorn --workers 5 --timeout 120 --bind $IP_ADDRESS:$PORT "superset.app:create_app()" --daemon
    if [[ $? -eq 0 ]]
    then
      echo -e "\033[32;1mSuperset has been restarted.\033[0m"
    else
      echo -e "\033[31;1mError happened when restarting the superset.\033[0m"
    fi
  else
    ps -ef | awk '/superset/ && !/awk/{print $2}' | xargs kill -9
    if [[ $? -eq 0 ]]
    then
      gunicorn --workers 5 --timeout 120 --bind $IP_ADDRESS:$PORT "superset.app:create_app()" --daemon
      if [[ $? -eq 0 ]]
      then
        echo -e "\033[32;1mSuperset has been restarted.\033[0m"
      else
        echo -e "\033[31;1mError happened when restarting the superset.\033[0m"
      fi
    fi
  fi
}

case $1 in
  "start")
    start
    running=1
    ;;
  "stop")
    stop
    running=0
    ;;
  "status")
    superset_status
    ;;
  "restart")
    superset_restart
    running=1
    ;;
  *)
    echo -e "\033[31;1mBad intput parameter.\033[0m"
    exit 1
    ;;
esac
